server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: spring-hot-plugin-demo
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**

# 开启调式日志
logging:
  level:
    csdn.itsaysay.plugin: DEBUG

#插件配置
plugin:
  runMode: prod
  backup-path: D:\javaprojects\spring-hot-plugin\spring-hot-plugin-example\plugin-path\back
  pluginPath: D:\javaprojects\spring-hot-plugin\spring-hot-plugin-example\plugin-path
