server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: spring-hot-plugin-demo
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**

# 开启调式日志
logging:
  level:
    csdn.itsaysay.plugin: debug

#插件配置
plugin:
  runMode: prod
  backup-path: E:\workspace\business-middle-platform\plugin-project\plugins\back
  pluginPath: /Users/chenjujun/greentown-projects/business-middle-platform/plugin-project/plugins/plugin-general
